### PR TITLE
Minor changes 

### PR DESCRIPTION
**Pull request by minouHub**
Hello,

I had to do the following changes to have the project working on my machine. 

1. Minor change in the import of matplotlib to avoid the warnings.
2. The function get_roi_info was bugging since the output of the function was an array and not a list.

Hope it's fine for you guys. Thanks for creating this project !
MinouHub

### CODE REVIEW

**Comment by emd** [comment]
With python 3.7.0 and numpy 1.15.2, I can confirm that `ashirsch:master` fails the automated regression testing but `minouHub:master` passes the regression testing (attributable to changing `roi` from an array to a list).

**Comment by erwanp** [comment]
This fix should be merged

**Comment by ashirsch** [comment]
Sorry for an extremely slow response - it's been a very long time since I had checked my old accounts. Happy you all are still using this utility :)

**Comment by minouHub** [comment]
That's fine. I'm so glad you merge this. Thanks !

**Pull request merged**
